# Generated by Django 5.1.7 on 2025-04-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_customer_group_payment_checklist_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='debt',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
