# Generated by Django 5.1.7 on 2025-05-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_payment_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='check_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
    ]
