# Generated by Django 5.1.7 on 2025-06-02 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customer_balance_alter_paymeninvoice_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='balance',
        ),
    ]
