# Generated by Django 5.1.7 on 2025-06-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customer_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='balance',
        ),
    ]
