# Generated by Django 5.1.7 on 2025-06-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_customer_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='balance_status',
            field=models.CharField(choices=[('A', 'Alacak'), ('B', 'Borç'), ('0', 'Denk')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='paymeninvoice',
            name='receivable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
